enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
riplib = true
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[X-piko]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
patches-source = "crimera/piko"
# included-patches = "'Hide For You' 'Hide Live Threads' 'Disable chirp font' 'Remove view count' 'Hide Banner' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Promoted Trends' 'Hide Community Notes' 'Google Ads Patch'"
integrations-source = "crimera/revanced-integrations"
# enabled = false

# [X-piko-dev]
# apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
# patches-source = "crimera/piko"
# included-patches = "'Hide For You' 'Hide Live Threads' 'Disable chirp font' 'Remove view count' 'Hide Banner' 'Hide FAB' 'Hide FAB Menu Buttons' 'Hide Promoted Trends' 'Hide Community Notes' 'Google Ads Patch'"
# integrations-source = "crimera/revanced-integrations"
# patches-version = "dev"
# enabled = false

